# Generated by Django 3.0.3 on 2020-06-02 18:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Autoshops',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=100, verbose_name='Адрес')),
                ('shop_name', models.CharField(max_length=45, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'Автомастерская',
                'verbose_name_plural': 'Автомастерские',
            },
        ),
        migrations.CreateModel(
            name='Car_Models',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_name', models.CharField(max_length=30, verbose_name='Марка авто')),
                ('engine_capacity', models.FloatField(verbose_name='Объем двигателя')),
                ('engine_power', models.FloatField(verbose_name='Мощность двигателя')),
            ],
            options={
                'verbose_name': 'Модель авто',
                'verbose_name_plural': 'Модели авто',
            },
        ),
        migrations.CreateModel(
            name='Cars',
            fields=[
                ('state_number', models.CharField(max_length=9, primary_key=True, serialize=False, verbose_name='Госномер')),
                ('year_of_issue', models.DateField(verbose_name='Год выпуска')),
                ('date_sheet_number', models.IntegerField(max_length=6, verbose_name='Номер техпаспорта')),
            ],
            options={
                'verbose_name': 'Автомобиль',
                'verbose_name_plural': 'Автомобили',
            },
        ),
        migrations.CreateModel(
            name='Costumer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name_c', models.CharField(max_length=50, verbose_name='ФИО')),
                ('address_c', models.CharField(max_length=100, verbose_name='Адрес')),
                ('phone_number_c', models.CharField(max_length=12, verbose_name='Номер телефона')),
                ('passport', models.IntegerField(max_length=10, verbose_name='Серия и номер паспорта')),
            ],
            options={
                'verbose_name': 'Владелец',
                'verbose_name_plural': 'Владельцы',
            },
        ),
        migrations.CreateModel(
            name='Masters',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name_m', models.CharField(max_length=50, verbose_name='ФИО')),
                ('phone_number', models.CharField(max_length=12, verbose_name='Номер телефона')),
                ('shop_number', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='autoApp.Autoshops', verbose_name='Автомастерская')),
            ],
            options={
                'verbose_name': 'Мастер',
                'verbose_name_plural': 'Мастера',
            },
        ),
        migrations.CreateModel(
            name='Comprehensive_Repair',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comrepair_date', models.DateField(auto_now_add=True, verbose_name='Дата регистрации комплексного ремонта')),
                ('state_number_r', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='autoApp.Cars', verbose_name='Госномер авто')),
            ],
            options={
                'verbose_name': 'Комплексный ремонт',
                'verbose_name_plural': 'Комплексные ремонты',
            },
        ),
        migrations.CreateModel(
            name='Completed_Works',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_of_repair', models.CharField(choices=[('IE', 'Replacing individual body elements'), ('P', 'Selecting paint and painting'), ('B', 'Replacing belts'), ('V', 'Adjusting valves'), ('OSC', 'Replacing oil scraper caps'), ('DG', 'Replacing drive and driven gears'), ('O', 'Replacing oil'), ('F', 'Replacing filters')], max_length=40, verbose_name='Вид ремонта')),
                ('receipt_date', models.DateTimeField(auto_now_add=True, verbose_name='Дата поступления авто на ремонт')),
                ('repair_completion_date', models.DateField(null=True, verbose_name='Дата завершения ремонта')),
                ('repair_cost', models.FloatField(null=True, verbose_name='Стоимость')),
                ('comrepair_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='autoApp.Comprehensive_Repair', verbose_name='Комплексный ремонт')),
                ('master_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='autoApp.Masters', verbose_name='Мастер')),
                ('shop_number_w', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='autoApp.Autoshops', verbose_name='Автомастерская')),
                ('state_number_w', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='autoApp.Cars', verbose_name='Госномер авто')),
            ],
            options={
                'verbose_name': 'Ремонтная работа',
                'verbose_name_plural': 'Ремонтные работы',
            },
        ),
        migrations.AddField(
            model_name='cars',
            name='costumer_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='autoApp.Costumer', verbose_name='Владелец авто'),
        ),
        migrations.AddField(
            model_name='cars',
            name='model_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='autoApp.Car_Models', verbose_name='Марка авто'),
        ),
        migrations.AddField(
            model_name='autoshops',
            name='car_models',
            field=models.ManyToManyField(to='autoApp.Car_Models', verbose_name='Обслуживаемые марки авто'),
        ),
    ]
