version: '3'
services:
  postgres:
    restart: always
    image: postgres:10
    environment:
      - POSTGRES_USER=Nastya
      - POSTGRES_PASSWORD=1234
      - POSTGRES_DB=autoshops
    volumes:
      - ./postgres-data/postgres:/var/lib/postgresql/data
    ports:
      - 51739:51739

  server:
    build:
      context: .
      dockerfile: ./Dockerfile
    command: python manage.py runserver 0.0.0.0:8000
    ports:
      - 8000:8000

  web:
    build:
      context: ./autoshops-vue/
      dockerfile: ./Dockerfile
    command: npm run dev
    network_mode: host
    ports:
      - 8080:8080
    depends_on:
      - server
